### ISSUE TITLE
Build fails on Windows 10

### ISSUE THREAD

**Issue by pcaston** [intel/iotivity-node#171]
I tried building iotivity node on windows 10 by following the Readme but I am getting this fatal error:
LINK : fatal error LNK1181: cannot open input file 'C:\Users\Paul\Documents\github\OpenPeerPower\iotivity-node\iotivity-installed\lib\octbstack.lib' [C:\Users\Paul\Documents\github\OpenPeerPower\iotivity-node\build\iotivity.vcxproj]
Here is the full log file:
[2018-02-04T13_51_56_129Z-debug.log](https://github.com/intel/iotivity-node/files/1692891/2018-02-04T13_51_56_129Z-debug.log)

**Comment by gabrielschulhof** [comment]
@pcaston are you installing iotivity-node from npm or from the github repo?

**Comment by pcaston** [comment]
From npm

**Comment by gabrielschulhof** [comment]
I have performed the following steps:

1. mkdir iotivity-node-test
2. cd iotivity-node-test
3. npm init (accept all defaults by pressing Enter)
4. npm install --save iotivity-node

This worked. That is, iotivity-node was successfully installed as a dependency of iotivity-node-test.

What precise steps are you performing which cause the failure for you?

**Comment by pcaston** [comment]
Having installed all the pre-reqs windows build tools, node, git, 7-zip, scons 
1.  I cloned the repository
2.  cd into iotivity-node
3.  Ran npm install - this failed with reported error
I didn't do the npm init.  I could try again tonight by following the video exactly - I followed the Readme.md file previously.

**Comment by pcaston** [comment]
@gabrielschulhof  I ran your instructions above but failed because of "error unable to create file filename too long" .  After I executed 'git config --system core.longpaths true' it worked!
Many thanks for your help.
